ISISComputingGroup/ibex_bluesky_core

- .gitignore
- README.md
- doc/architectural_decisions/001-repo-structure.md
- doc/architectural_decisions/002-use-ophyd-async.md
- doc/architectural_decisions/003-run-in-process.md
- pyproject.toml
- ruff.toml
- src/ibex_bluesky_core/__init__.py
- src/ibex_bluesky_core/demo_plan.py
- src/ibex_bluesky_core/devices/__init__.py
- src/ibex_bluesky_core/devices/block.py
- src/ibex_bluesky_core/devices/dae.py
- src/ibex_bluesky_core/plan_stubs/__init__.py
- tests/devices/test_block.py
- tests/devices/test_dae.py
- tests/devices/test_init.py
A minimal starting point for this repository.
To review:
- Check you can follow the instructions in the `README` to set up a development environment.
- Check the initial unit tests pass
- Check the initial (minimal set) of functionality works
* Note: none of this is necessarily has to be the _final_ way of doing things or structure - the goal of this PR is to have a starting point onto which future pull requests can build. Therefore the functionality in this PR is an extremely minimal implementation of a block and DAE.
- Check you can run the example in `demo_plan` by running: 
```
python -c "from ibex_bluesky_core.demo_plan import run_demo_plan;run_demo_plan()"
```
* This is not necessarily how we will end up running our plans - it exists at this point to show the block and dae devices …
> Initial structure

- doc/conf.py
- pyproject.toml
- src/ibex_bluesky_core/devices/block.py
- src/ibex_bluesky_core/devices/simpledae/waiters.py
Increase nitpickyness in docs build. Basically if we refer to `ibex_bluesky_core.*` in the docs, then check those references actually resolve to the API docs.
> Be nitpicky

- doc/fitting/fitting.md
- src/ibex_bluesky_core/callbacks/fitting/fitting_utils.py
- tests/callbacks/fitting/test_fitting_methods.py
Slit scan guess was sometimes struggling to converge due to initial guesses outside of the data, this causes all differentials to go to zero for some parameters and hence optimizer cannot work.
Simplified heuristic guessing function that keeps all initial parameters within the bounds of the data seemed to work well to give the optimizer a good chance of converging to a decent fit.
Updates unit tests.
To test make sure that all unit tests pass.
> fixes slit scan guess & unit tests

- .github/workflows/Lint-and-test.yml
- tests/callbacks/test_write_log_callback.py
Merge https://github.com/ISISComputingGroup/ibex_bluesky_core/pull/81 first
> Are we ready for 3.12 yet?

- doc/devices/blocks.md
- src/ibex_bluesky_core/devices/block.py
- tests/devices/test_block.py
Closes https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/77
> Add option to wait for global moving flag

- doc/callbacks/file_writing.md
- manual_system_tests/dae_scan.py
- src/ibex_bluesky_core/callbacks/file_logger.py
- src/ibex_bluesky_core/callbacks/fitting/livefit_logger.py
- tests/callbacks/fitting/test_fit_logging_callback.py
- tests/callbacks/test_write_log_callback.py
> Default Filename and Location

- src/ibex_bluesky_core/devices/dae/dae.py
no longer needed - we explicitly make these when needed
> remove spectra_1_period_1 from dae

- doc/dev/set_up_dev_environment.md
ophyd-async has recently added https://blueskyproject.io/ophyd-async/main/how-to/choose-right-baseclass.html so thought i'd add some developer resources that might be useful to reference when writing stuff for IBC.
> add some developer resources

- .github/codeql/codeql-config.yml
- .github/workflows/Lint-and-test.yml
Reverts ISISComputingGroup/ibex_bluesky_core#124
now done by reusable workflow instead
> Revert "codeql"

- src/ibex_bluesky_core/devices/block.py
- src/ibex_bluesky_core/devices/dae/dae_controls.py
- src/ibex_bluesky_core/devices/dae/dae_period_settings.py
- src/ibex_bluesky_core/devices/dae/dae_settings.py
- src/ibex_bluesky_core/devices/dae/dae_tcb_settings.py
fixes the pyright issues that you probably see on every branch at the moment. 
@Tom-Willemsen  i've put the block ones in here as well as i think they might cut down your PR a bit
> fix pyright issues - missing types for Movable, Locatable on block and dae settings

- src/ibex_bluesky_core/devices/reflectometry/__init__.py
see https://github.com/ISISComputingGroup/EPICS-refl/blob/master/ReflectometryServer/ChannelAccess/pv_manager.py#L89
> typo in DEFINE_POS_SP

- src/ibex_bluesky_core/log.py
https://github.com/ISISComputingGroup/ibex_bluesky_core/security/code-scanning/1
> codeql warning fix

- .github/workflows/Lint-and-test.yml
- .github/workflows/test-against-main.yml
- src/ibex_bluesky_core/devices/block.py
- src/ibex_bluesky_core/plans/__init__.py
- tests/callbacks/fitting/test_fitting_methods.py
- tests/devices/test_block.py
- Updates the name of "test-against-main" to "future-dependency-compatibility-test".
- Updates what "lint-and-test-nightly" does. Used to test against changes but it there was never any changes (comparing main to main) now tests the whole codebase.
- Does a bunch of pyright fixes
> Update workflows & fix pyright issues

- doc/plan_stubs/redefining.md
- src/ibex_bluesky_core/devices/reflectometry/__init__.py
- src/ibex_bluesky_core/plan_stubs/__init__.py
- tests/test_plan_stubs.py
something we had to do on POLREF
> allow redefine to be optional for refl param

- src/ibex_bluesky_core/devices/simpledae/__init__.py
- src/ibex_bluesky_core/plans/reflectometry/_autoalign.py
Removes ignores which are not actually supressing any errors
> Remove ignores

- src/ibex_bluesky_core/callbacks/_fitting.py
> put fit reports in fitting dir

- doc/callbacks/plotting.md
*Add your own description here*
Closes #132 by documenting it?
> add docs for PlotPNGSaver

- .github/workflows/lint-and-test-nightly.yml
allow manually running nightly build
> allow manually running nightly build

- manual_system_tests/dae_scan.py
earlier in this test it sets up a RunPerPointController, so this is unnecessary
> remove set num periods in dae_scan.py

- doc/architectural_decisions/003-run-in-process.md
> update ADR to include run_plan

- doc/fitting/standard_fits.md
Correct a couple of typos
*Link to Ticket*
*List the acceptance criteria for the PR. The aim is provide information to help the reviewer*
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the reviewer*
> Correct typos
