pyproject.toml
src/ibex_bluesky_core/demo_plan.py
src/ibex_bluesky_core/run_engine.py
tests/test_run_engine.py

Create a run engine, and add basic tests for run engine functionality.
https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/2
To review:
- Check demo plan works
- Check tests & linting pass (this will soon be done by CI, but as CI is not merged yet, it needs to be checked manually)
- Check as a developer you agree with the initial basic set of tests for bluesky run engine functionality (the goal is not to exhaustively test it, but to check we've configured it in a sane way)
- Check as a developer basic interactive run engine functionality works - e.g. run a plan, interrupt it, add a custom callback, etc.
Notes:
- The custom `_DuringTask` has been pushed upstream (https://github.com/bluesky/bluesky/pull/1770); if & when that PR gets merged & released we can remove our version

Create run engine

---

.github/workflows/Lint-and-test.yml
doc/docs_logging_callback.md
src/ibex_bluesky_core/callbacks/__init__.py
src/ibex_bluesky_core/callbacks/document_logger.py
src/ibex_bluesky_core/run_engine.py
tests/conftest.py
tests/test_document_logging_callback.py
tests/test_run_engine.py

- Creates a new callback function that the BlueSky run engine subscribes to which records every document in a log file under "C:\\","instrument","var","logs","bluesky","raw_documents".
- Added a unit test that checks that the file to be written to is opened 3 times, for open, descriptor then stop. Also in the stop document to be written, checks that the run is successful with no interruptions.
- Callback returns an ID of 0 if it is ever needed to unsubscribe
[Ticket6](https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/6#issue-2437829032)

Added document logging & unit tests

---

doc/fitting/fitting.md
doc/fitting/standard_fits.md
src/ibex_bluesky_core/callbacks/fitting/fitting_utils.py
tests/callbacks/fitting/test_fitting_methods.py

Found issues with linear fitting whereby the guess function would not work as expected e.g not guessing a straight line and division by zero error. This fixes by instead using the already implemented polynomial guess function and passing 1 as the polynomial degree. Should test by creating an example plan and two blocks to scan against eachother from- use a python script to repeatedly write to one of the blocks to simulate data from scan. See below. Check that initial guess produced in plot window fits the data provided well.
See [fitting docs](https://isiscomputinggroup.github.io/ibex_bluesky_core/fitting/fitting.html) for more info.
Run this separately
```
def linear(x, m, c):
return m * x + c
g.set_pv("CS:SB:bob", 1, is_local=True)
while True:
val = g.get_pv("CS:SB:bob", is_local=True) …
```

Fixes issues found with linear fitting guess function

---

README.md
doc/architectural_decisions/004-use-scipp.md
doc/dev/logging.md
doc/index.rst

- Minor tidying/formatting of docs
- Add an intro section giving a bit of context around what this is for

Tidy up docs; add an intro

---

doc/index.rst
doc/plan_stubs/external_code.md
src/ibex_bluesky_core/plan_stubs/__init__.py
src/ibex_bluesky_core/run_engine/__init__.py
src/ibex_bluesky_core/run_engine/_msg_handlers.py
tests/test_plan_stubs.py

https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/43
Contrary to what the ticket said, I did actually end up writing some code rather than just documentation here. My initial plan was to simply not allow keyboard interrupts, but on further thought I think a best-efforts mechanism, while not _perfect_ is better than nothing.
There's some fiddly code in this PR so please review carefully and make sure it is understandable for the average developer.

Add helper for external blocking functions

---

.github/workflows/test-against-main.yml

may close #49 
this is difficult to test as [the action will only work on the main branch](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule):
> This event will only trigger a workflow run if the workflow file is on the default branch.

add action for checking every day against ophyd-async and bluesky main branches

---

doc/index.rst
doc/tutorial/overview.md

Expand tutorial documentation to walk through what plans & devices are, how to set/read/scan devices, how to execute a scan from the run engine, how to specify callbacks.
A lot of the "heavy lifting" should be done in lower-level documentation, the goal is to keep this page readable for a first-time bluesky user.
Closes https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/55

Add tutorial

---

doc/conf.py

needed to get rid of warning that https://github.com/ISISComputingGroup/reusable-workflows/pull/10 will fail the build on.

remove sphinx static dir

---

.github/workflows/release.yml

Last release [failed sigstore](https://github.com/ISISComputingGroup/ibex_bluesky_core/actions/runs/12064270880/job/33687930925), bump it up a version as per [updated pypa recommendation](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) to see if that helps.
If so, will make an equivalent pr on `genie` too.

Bump sigstore

---

doc/callbacks/plotting.md
doc/plan_stubs/matplotlib_helpers.md
manual_system_tests/dae_scan.py
src/ibex_bluesky_core/plan_stubs/__init__.py
src/ibex_bluesky_core/run_engine/__init__.py
src/ibex_bluesky_core/run_engine/_msg_handlers.py
tests/test_plan_stubs.py

Fixes https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/92
Calling `plt.subplots` directly in a plan breaks, if the matplotlib backend is `qt` (e.g. if running a plan in a standalone shell).
That's because it would try to interact with the Qt gui from the RunEngine's plan worker thread, which is invalid. Instead we need to force it to go through bluesky's matplotlib-qt integration infrastructure.
To review:
- Run manual dae_scan plan in IBEX
- Run manual dae_scan plan in a standalone window (this _doesn't_ currently work on `main`)
- Both cases above should run and display plots
- Docs are clear enough

Helper to create a new figure/axes in a qt-safe way

---

tests/callbacks/fitting/test_fitting_methods.py
tests/devices/test_block.py

see https://github.com/ISISComputingGroup/ibex_bluesky_core/actions/runs/13125534709/job/36621002077 
two of these are covered by #98

ruff fixes

---

src/ibex_bluesky_core/callbacks/_utils.py
src/ibex_bluesky_core/callbacks/file_logger.py
src/ibex_bluesky_core/callbacks/fitting/livefit_logger.py
tests/callbacks/fitting/test_fit_logging_callback.py
tests/callbacks/test_write_log_callback.py

this fixes an exception that occurs when the HumanReadableFileCallback tries to create a file if the parent directory does not exist. 
Closes #99

fix exception if output file (rbnum) dir doesn't exist

---

tests/devices/simpledae/test_controllers.py
tests/devices/simpledae/test_reducers.py
tests/devices/simpledae/test_waiters.py
tests/devices/test_block.py
tests/devices/test_dae.py
tests/test_preprocessors.py

`ophyd-async` got a new release recently and as a result our imports to their testing utils became wrong.

Fixes ophyd-async testing imports

---

src/ibex_bluesky_core/devices/reflectometry/__init__.py
tests/devices/test_reflectometry.py
tests/test_plan_stubs.py

found when we wrote the initial top level plan on polref - the refl server helpfully never updates a monitor so CHANGED never actually gets set...

Remove wait for CHANGED on a refl param redefine

---

doc/plan_stubs/external_code.md
src/ibex_bluesky_core/plan_stubs/__init__.py

Closes https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/137
> The `call_sync` plan stub no longer clears an active checkpoint. This means that plans using `call_sync` which are stopped by a keyboard interrupt will now be resumable.

Remove clear_checkpoint from call_sync

---

README.md

Since we do now have technique-specific things

Remove reference to "not technique specific"

---

doc/architectural_decisions/001-repo-structure.md
doc/architectural_decisions/002-use-ophyd-async.md
doc/architectural_decisions/003-run-in-process.md
doc/architectural_decisions/004-use-scipp.md
doc/architectural_decisions/005-variance-addition.md
doc/architectural_decisions/006-where-to-put-code.md
doc/conf.py

Reword/clarify a couple of ADRs.
**No substantive change to the decision(s) they document**, just:
- Clarifying that parts of ADR 1 are now superseded by ADR 6
- Expanding/clarifying the text of ADR 4 as I got some feedback from another group it wasn't entirely clear
- Various minor edits, adding links etc for clarity

Reword adrs

---

.gitignore
pyproject.toml
src/ibex_bluesky_core/callbacks/__init__.py
src/ibex_bluesky_core/run_engine/__init__.py
tests/test_run_engine.py

Add the version of `ibex_bluesky_core` as metadata in the re for traceability

Add version as metadata

---

src/ibex_bluesky_core/callbacks/__init__.py
src/ibex_bluesky_core/callbacks/_fitting.py
src/ibex_bluesky_core/callbacks/_plotting.py
src/ibex_bluesky_core/plans/reflectometry/_autoalign.py
src/ibex_bluesky_core/plans/reflectometry/_det_map_align.py
src/ibex_bluesky_core/run_engine/__init__.py
src/ibex_bluesky_core/run_engine/_msg_handlers.py
src/ibex_bluesky_core/utils.py
tests/callbacks/test_isis_callbacks.py
tests/plans/test_reflectometry.py
tests/test_utils.py

Closes https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/153
- Adds an option to `LivePlot` to only plot at end
- Make refl detector-mapping stuff only fit at end
- Make sure we're not using [Schlemiel's algorithm](https://en.wikichip.org/wiki/schlemiel_the_painter%27s_algorithm) for error bar rendering
- Some Qt nonsense, because every PR needs some Qt nonsense
For a test case on my machine with ~1280 events, this reduces time spent on fitting/plotting callbacks from ~30s to ~1s

Optometrise

---

doc/plans/plans.md
src/ibex_bluesky_core/plans/__init__.py
tests/plans/test_init.py

This PR makes the motor_scan() and motor_adaptive_scan() consturct a BlockRw using the global moving flag. this change is required as if you try and use motor_scan() over something that is using axis.cmd it doesn't have all of the motor fields and then fails to connect to a load of fields that don't exist. this is what the SANS instruments want to do for most cases, so i think we should cater for it.

use blockrw for motor scan instead of block_mot

---

doc/plan_stubs/polling.md
doc/plans/plans.md
src/ibex_bluesky_core/plan_stubs.py
src/ibex_bluesky_core/plans/__init__.py
tests/plans/test_init.py

this moves polling_plan (annoyingly named _plan!) to plan_stubs, but keeps in the __all__ of plans for backwards compatibility on LOQ.

remove run decorator from polling plan

---

src/ibex_bluesky_core/devices/__init__.py
src/ibex_bluesky_core/devices/reflectometry.py
tests/devices/test_reflectometry.py
tests/test_plan_stubs.py

This adds an exception for when trying to redefine a reflectometry parameter if the instrument is not in manager mode. 
As our plans/plan stubs don't do any redefining in this library other than redefine_refl_param() which will feed-through the exception I think this is all we need to do - IMO it should actually halt a plan and therefore the exception doesn't need to be caught on the top-level plan. This should mean it's a bit more readable to the user that their redefine has failed.
Closes #146  and probably #189 
*Add appropriate label(s) to this PR*
- 'bluesky-Semver-Major' - Breaking Change
- 'bluesky-Semver-Minor' - New feature
- 'bluesky-bug' - Bug fix
- 'bluesky-documentation' - Document Changes
- 'bluesky-ignore-for-release' - Do not show in the release notes 
**Labels can be …

raise exception if not in manager mode

---

doc/plan_stubs/redefining.md
src/ibex_bluesky_core/plan_stubs.py

Closes https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/191
https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/191
- 'bluesky-bug' - Bug fix
Redefining a motor and then immediately moving it works
See PR

Sleep by default after motor redefine

---

.github/workflows/check_pr_has_label.yml

Add a check to ensure PRs can't be merged without a release label.
None
*Add appropriate label(s) to this PR*
- 'bluesky-Semver-Major' - Breaking Change
- 'bluesky-Semver-Minor' - New feature
- 'bluesky-bug' - Bug fix
- 'bluesky-documentation' - Document Changes
- 'bluesky-ignore-for-release' - Do not show in the release notes 
bit meta ;)
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the reviewer*

Enforce adding release-note labels to PRs

---

doc/devices/blocks.md
src/ibex_bluesky_core/devices/block.py
tests/devices/test_block.py

Fixes the future-dependencies build. Upstream ophyd-async has added motor-limits checking (in https://github.com/bluesky/ophyd-async/pull/1032).
n/a
*Add appropriate label(s) to this PR*
- 'bluesky-Semver-Major' - Breaking Change
- 'bluesky-Semver-Minor' - New feature
- 'bluesky-bug' - Bug fix
- 'bluesky-documentation' - Document Changes
- 'bluesky-ignore-for-release' - Do not show in the release notes 
**Labels can be found of the right-hand sidebar of this PR once created**
*List the acceptance criteria for the PR. The aim is provide information to help the reviewer*
Docs added to highlight to users that motor limits will be checked for a `BlockMot`.

Motor limits are now checked by `ophyd-async`
